name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        env:
          CGO_ENABLED: "0"
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="-s -w" -o dhcp-probe-linux-${{ matrix.goarch }} .

      - name: Upload build artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: dhcp-probe-linux-${{ matrix.goarch }}
          path: dhcp-probe-linux-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu

    steps:
      - name: Download all build artifacts
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          path: dist/release

      - name: Flatten artifacts into release dir
        run: |
          find dist/release -type f -exec mv {} dist/release/ \;
          find dist/release -mindepth 1 -type d -delete

      - name: Upload release artifacts
        uses: https://data.forgejo.org/actions/forgejo-release@v2
        with:
          direction: upload
          release-dir: dist/release
          token: ${{ secrets.GITHUB_TOKEN }}
